#!/bin/zsh


eval `gnome-keyring-daemon --start`; export SSH_AUTH_SOCK

# if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
if [ "$(fgconsole 2> /dev/null)" = 1 ]; then
  if [ -f "$HOME/.xinitrc" ]; then
    rm $HOME/.xorg.log
    startx 2>&1 > $HOME/.xorg.log
    logout
  fi
  # (startx &); logout
  # (startx xfce &); logout
fi

# if [ `uname` = Darwin -a ! -f /tmp/userconf_inited_boot ]; then
#   echo "please enable pf && run ssh-add"
# fi


# path=(
#   "$HOME/.local/go/bin"
#   $path
# )
# export PATH

# export HOMEBREW_AUTO_UPDATE_SECS=999999999
# export HOMEBREW_NO_GITHUB_API=1
# export HOMEBREW_NO_ANALYTICS=1

source $HOME/.dotfiles/zshrc
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

active_asdf() {
  source $HOME/.asdf/asdf.sh
  source $HOME/.asdf/completions/asdf.bash
}

active_ghcup() {
  export PATH=$HOME/.ghcu/bin:$PATH
}

active_nix() {
  source $HOME/.nix-profile/etc/profile.d/nix.sh
}

pgcli() { $HOME/.local/opt/pyenv/pgcli/bin/pgcli $@ }
mycli() { $HOME/.local/opt/pyenv/pgcli/bin/mycli $@ }
litecli() { $HOME/.local/opt/pyenv/pgcli/bin/litecli $@ }

alias vim=nvim
alias gvim=nvim-qt

export LS_COLORS="$(vivid -m 8-bit generate jellybeans)"

#alias mc=mcli

export _JAVA_OPTIONS=" -XX:ActiveProcessorCount=4 $_JAVA_OPTIONS"
export ANDROID_HOME=~/.local/android/sdk
