#!/bin/zsh

# if [ -z "$DISPLAY" ] && [ $(tty) = /dev/tty1 ]; then
if [ "$(fgconsole 2> /dev/null)" = 1 ]; then
  startx
  logout
  # (startx &); logout
  # (startx xfce &); logout
fi

active_rbenv()
{
  export PATH="$HOME/.rbenv/bin:$PATH"
  export RUBY_BUILD_SKIP_MIRROR=1
  export RUBY_BUILD_CACHE_PATH=$HOME/.local/unix
  eval "$(rbenv init -)"
  rbenv rehash
  rehash

  # option for `./configure` ruby
  # CONFIGURE_OPTS="--disable-install-rdoc"
}

# export VIRTUAL_ENV_DISABLE_PROMPT=1
# #source $HOME/.local/python/env/27/bin/activate

# export NODE_VIRTUAL_ENV_DISABLE_PROMPT=1

# #export NODE_PATH=`npm -g root`
# eval "$(npm completion 2>/dev/null)"

# path=(
#   "$HOME/.local/opt/scala/bin"
#   "$HOME/.local/opt/sbt"
#   "$HOME/.local/opt/play"
#   "$HOME/.local/opt/akka/bin"
#   $path
# )
# export PATH


# sbt options
# export SBT_OPTS='-Xms128m -Xmx512m -Xss1m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -XX:ReservedCodeCacheSize=192m'

source $HOME/.dotfiles/zshrc

