#!/usr/bin/env sh

bspc rename Desktop01 1
bspc add 2 3 4 5 6 7 8 9

bspc rule Inkscape floating
bspc rule Gimp floating
# bspc rule Smplayer floating

bspc set outer_border_width  3 #3
bspc set main_border_width   1 #1
bspc set inner_border_width  1 #3
bspc set window_gap          3 #15
bspc set top_padding         15 #24

bspc set borderless_monocle  true

