#!/usr/bin/env sh

bspc rename Desktop01 One
bspc add Two Three Four Five Six Seven Eight Nine Ten

bspc rule Inkscape floating
bspc rule Gimp floating
bspc rule MyPaint floating
bspc rule fontforge floating
bspc rule processing-app-Base floating

bspc set outer_border_width  3 #3
bspc set main_border_width   1 #1
bspc set inner_border_width  1 #3
bspc set window_gap          3 #15
bspc set top_padding         15 #24

bspc set borderless_monocle  true

