


ascii_composer:
  switch_key:
    Control_L: noop
    Control_R: noop
    Shift_L: inline_ascii
    Shift_R: commit_text

key_binder:
  bindings:
    - accept: "Control+p"
      send: Up
      when: composing
    - accept: "Control+n"
      send: Down
      when: composing
    - accept: "Control+b"
      send: Left
      when: composing
    - accept: "Control+f"
      send: Right
      when: composing
    - accept: "Control+a"
      send: Home
      when: composing
    - accept: "Control+e"
      send: End
      when: composing
    - accept: "Control+d"
      send: Delete
      when: composing
    - accept: "Control+k"
      send: "Shift+Delete"
      when: composing
    - accept: "Control+g"
      send: Escape
      when: composing
    - accept: "Alt+v"
      send: Page_Up
      when: composing
    - accept: "Control+v"
      send: Page_Down
      when: composing
    - accept: ISO_Left_Tab
      send: Page_Up
      when: composing
    - accept: "Shift+Tab"
      send: Page_Up
      when: composing
    - accept: Tab
      send: Page_Down
      when: composing
    - accept: minus
      send: Page_Up
      when: paging
    - accept: equal
      send: Page_Down
      when: has_menu
    - accept: comma
      send: Page_Up
      when: paging
    - accept: period
      send: Page_Down
      when: has_menu

punctuator:
  full_shape:
    " ":
      commit: "　"
    "!":
      commit: "！"
    "\"":
      pair:
        - "“"
        - "”"
    "#":
      - "＃"
      - "#"
      - "⌘"
    "$":
      - "￥"
      - "$"
      - "€"
      - "£"
      - "¥"
      - "¢"
      - "¤"
    "%":
      - "％"
      - "%"
      - "°"
      - "℃"
    "&":
      - "＆"
      - "&"
    "'":
      pair:
        - "‘"
        - "’"
    "(": "（"
    ")": "）"
    "*":
      - "＊"
      - "*"
      - "・"
      - "×"
      - "※"
      - "❂"
      - "·"
    "+":
      - "＋"
      - "+"
    ",":
      commit: "，"
    "-":
      - "－"
      - "-"
    .:
      commit: "。"
    "/":
      - "／"
      - "/"
      - "÷"
    ":": "："
    ";":
      commit: "；"
    "<":
      - "《"
      - "〈"
      - "«"
      - "‹"
    "=":
      - "＝"
      - "="
    ">":
      - "》"
      - "〉"
      - "»"
      - "›"
    "?":
      commit: "？"
    "@":
      - "＠"
      - "@"
      - "☯"
    "[":
      - "「"
      - "【"
      - "〔"
      - "［"
    "\\":
      - "、"
      - "＼"
      - "\\"
    "]":
      - "」"
      - "】"
      - "〕"
      - "］"
    "^":
      commit: "……"
    _: "——"
    "`":
      - "｀"
      - "`"
    "{":
      - "『"
      - "〖"
      - "｛"
    "|":
      - "・"
      - "｜"
      - "|"
      - "§"
      - "¦"
    "}":
      - "』"
      - "〗"
      - "｝"
    "~":
      - "〜"
      - "~"
      - "～"
      - "〰"
  half_shape:
    "," : { commit: "," }
    "." : { commit: "." }
    "<" : "<"
    ">" : ">"
    "/" : "/"
    "?" : { commit: "?" }
    ";" : { commit: ";" }
    ":" : { commit: ":" }
    "'" : "'"
    "\"" : "\""
    "\\" : "\\"
    "|" : "|"
    "`" : "`"
    "~" : "~"
    "!" : { commit: "!" }
    "@" : "@"
    "#" : "#"
    "%" : "%"
    "$" : "$"
    "^" : "^"
    "&" : "&"
    "*" : "*"
    "(" : "("
    ")" : ")"
    "-" : "-"
    "_" : "_"
    "+" : "+"
    "=" : "="
    "[" : "["
    "]" : "]"
    "{" : "{"
    "}" : "}"

recognizer:
  patterns:
    email: "^[a-z][-_.0-9a-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp:|mailto:).*$|^[a-z]+[.].+$"

schema_list:
  - schema: luna_pinyin
  - schema: luna_pinyin_fluency
  - schema: luna_pinyin_simp

switcher:
  caption: "〔方案選單〕"
  hotkeys:
    - "Control+grave"
#    - "Control+Shift+grave"
#    - F4
  save_options:
    - full_shape
    - simplification
    - extended_charset

menu:
  page_size: 6
